# w YAML bardzo wazne sa spacje i odleglosci
guru:
  jms:
    username: JMS Username
    password: somepass
    url: SomeUrl

---
spring:
  profiles: es
guru:
  jms:
    username: JMS Username $$$$$$ SPANISH